<a href="https://colab.research.google.com/github/SnigdhaSaklani/SnigdhaSaklani-python./blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Load the NumPy

import numpy as np
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[37 35]
 [16 29]
 [26 22]
 [36 13]
 [10 24]
 [20 38]
 [21 10]
 [25 19]]
 
 The shape of the array is (8, 2)


In [11]:
#Storing the transpose in another matrix object

nilgiri = np.transpose(arravali)
print(f" This transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 This transpose of the array is 
[[37 16 26 36 10 20 21 25]
 [35 29 22 13 24 38 10 19]]
 
 The shape of the array is (2, 8)


In [13]:
#3D Array

random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[27 26 34 43]
  [12 17 30 34]]

 [[27 39 19 35]
  [18 10 22 20]]

 [[19 41 41 42]
  [39 23 40 18]]]
 
 The shape of the array is (3, 2, 4)


In [16]:
#Storing the transpose of the created 3D Array

transpose_3d_array = np.transpose(random_3d_array)
print(f" This transpose of the array is \n{transpose_3d_array}")
print(f" \n The shape of the array is {transpose_3d_array.shape}")

 This transpose of the array is 
[[[27 27 19]
  [12 18 39]]

 [[26 39 41]
  [17 10 23]]

 [[34 19 41]
  [30 22 40]]

 [[43 35 42]
  [34 20 18]]]
 
 The shape of the array is (4, 2, 3)


In [18]:
#Create a two dimensional array

random_cohort = np.array(np.random.randint(10,45,(3,8)))
print(f"The defined array is \n{random_cohort}")
print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[20 42 34 17 40 42 16 24]
 [25 19 27 17 43 36 40 22]
 [28 32 16 26 25 18 28 19]]
 
 The shape of the array is (3, 8)


In [20]:
#Now we can reshape this to 1D,2D or 3D Array

new_shape = (2,6,2)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[20 42]
  [34 17]
  [40 42]
  [16 24]
  [25 19]
  [27 17]]

 [[43 36]
  [40 22]
  [28 32]
  [16 26]
  [25 18]
  [28 19]]]
 
 The shape of the array is (2, 6, 2)


In [21]:
new_shape = (2,-1,6)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[20 42 34 17 40 42]
  [16 24 25 19 27 17]]

 [[43 36 40 22 28 32]
  [16 26 25 18 28 19]]]
 
 The shape of the array is (2, 2, 6)


In [22]:
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[37 41]
  [35 33]
  [11 19]
  [26 16]
  [24 37]
  [15 11]]

 [[36 11]
  [21 21]
  [37 42]
  [19 42]
  [32 12]
  [21 35]]

 [[11 16]
  [39 39]
  [20 37]
  [44 29]
  [18 10]
  [25 21]]]
 
 The shape of the array is (3, 6, 2)


In [23]:
new_shape = (2,1,6)
resize_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[37 41 35 33 11 19]]

 [[26 16 24 37 15 11]]]
 
 The shape of the array is (2, 1, 6)


In [24]:
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[33 15 39 34 41 21]
  [42 22 10 22 11 16]
  [27 33 39 10 42 31]
  [28 19 21 29 17 43]]

 [[42 14 25 12 12 26]
  [33 15 20 21 41 36]
  [36 35 44 41 27 34]
  [42 34 36 29 10 40]]]
 
 The shape of the array is (2, 4, 6)


In [25]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[37 41 35 33 11 19]]

 [[26 16 24 37 15 11]]]
 
 The shape of the array is (2, 1, 6)


In [29]:
import numpy as np
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[20 25 28 23 17 40]
  [41 14 34 38 24 34]
  [21 39 24 39 24 27]
  [40 32 25 18 28 36]]

 [[10 11 34 23 36 22]
  [20 25 10 12 21 25]
  [38 19 18 27 12 18]
  [26 32 29 40 17 20]]]
 
 The shape of the array is (2, 4, 6)


In [30]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

This resized array is 
[[[20 25 28 23 17 40]
  [41 14 34 38 24 34]
  [21 39 24 39 24 27]]

 [[40 32 25 18 28 36]
  [10 11 34 23 36 22]
  [20 25 10 12 21 25]]]
 
 The shape of the array is (2, 3, 6)


In [31]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))   #Axis 0-2 ; Axis 1-3 ; Axis 2-4
print(a)
print(a.shape)

[[[16 11 12 12]
  [11 17 12 16]
  [12 14 10 10]]

 [[19 11 12 14]
  [10 13 18 17]
  [17 18 10 19]]]
(2, 3, 4)


In [32]:
#Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[ 16,  11,  12,  12],
        [ 11,  17,  12,  16],
        [ 12,  14,  10,  10]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 19,  11,  12,  14],
        [ 10,  13,  18,  17],
        [ 17,  18,  10,  19]]])

In [33]:

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 2 3]
  [3 2 4]
  [3 2 2]]

 [[5 4 3]
  [4 5 4]
  [4 5 5]]]
(2, 3, 3)


In [34]:
np.append(a,50)

array([ 2,  2,  3,  3,  2,  4,  3,  2,  2,  5,  4,  3,  4,  5,  4,  4,  5,
        5, 50])

In [35]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[3 3 5]]

 [[4 3 5]]]


In [36]:
print(a)
print(a.shape)

[[[2 2 3]
  [3 2 4]
  [3 2 2]]

 [[5 4 3]
  [4 5 4]
  [4 5 5]]]
(2, 3, 3)


In [37]:
np.append(a,b,axis=1)

array([[[2, 2, 3],
        [3, 2, 4],
        [3, 2, 2],
        [3, 3, 5]],

       [[5, 4, 3],
        [4, 5, 4],
        [4, 5, 5],
        [4, 3, 5]]])

In [38]:
import numpy as np
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 5 4]
  [5 3 2]
  [5 3 2]]

 [[4 2 5]
  [3 2 3]
  [5 3 5]]]
(2, 3, 3)


In [39]:
np.delete(a,(0),axis = 0)

array([[[4, 2, 5],
        [3, 2, 3],
        [5, 3, 5]]])

In [40]:
np.delete(a,(0,2),axis = 1)

array([[[5, 3, 2]],

       [[3, 2, 3]]])

In [41]:
a

array([[[5, 5, 4],
        [5, 3, 2],
        [5, 3, 2]],

       [[4, 2, 5],
        [3, 2, 3],
        [5, 3, 5]]])

In [42]:
np.delete(a,(0,1),axis = 2)

array([[[4],
        [2],
        [2]],

       [[5],
        [3],
        [5]]])

In [43]:

a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[ 8  6 18]
  [14 10 19]
  [ 9 18  6]]

 [[11 11  6]
  [ 2 16 10]
  [ 8  9 14]]]
(2, 3, 3)


In [44]:
np.unique(a)

array([ 2,  6,  8,  9, 10, 11, 14, 16, 18, 19])

In [45]:
np.unique(a,return_counts=True)

(array([ 2,  6,  8,  9, 10, 11, 14, 16, 18, 19]),
 array([1, 3, 2, 2, 2, 2, 2, 1, 2, 1]))

In [46]:
np.unique(a,return_counts=True,return_index=True)

(array([ 2,  6,  8,  9, 10, 11, 14, 16, 18, 19]),
 array([12,  1,  0,  6,  4,  9,  3, 13,  2,  5]),
 array([1, 3, 2, 2, 2, 2, 2, 1, 2, 1]))

In [47]:
a = [1,2,3]
b= a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [48]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [49]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [50]:
np.arange(3) + 5

array([5, 6, 7])

In [51]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [52]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [53]:
np.arange(2)

array([0, 1])

In [54]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[5 2 5 5]
 [3 3 3 5]]
[[4 2]
 [4 4]]


In [55]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)

[[5 2 3 2]
 [5 3 3 2]]
[[3 3 1 4]
 [0 3 1 3]]


In [56]:
np.multiply(a,b)

array([[15,  6,  3,  8],
       [ 0,  9,  3,  6]])

In [57]:
np.divide(a,b)

<ipython-input-57-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[1.66666667, 0.66666667, 3.        , 0.5       ],
       [       inf, 1.        , 3.        , 0.66666667]])

In [58]:
a=np.random.randint(5,9,(2,4))
print(a)

[[6 6 6 7]
 [7 8 7 8]]


In [59]:
print(np.sum(a))
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))

55
[13 14 13 15]
[25 30]


In [60]:
print(np.min(a))
print(np.min(a,axis=1)) #Across Column
a =np.random.randint(0,20,(3,3))
print(a)

6
[6 7]
[[11 19 14]
 [ 2  6 16]
 [ 1 19 10]]


In [61]:
print(np.sort(a,axis=0)) # Ascending

[[ 1  6 10]
 [ 2 19 14]
 [11 19 16]]


In [62]:
print(np.sort(a,axis=1))

[[11 14 19]
 [ 2  6 16]
 [ 1 10 19]]


In [63]:
print(-np.sort(-a,axis=1)) #Descending

[[19 14 11]
 [16  6  2]
 [19 10  1]]


In [64]:
sum(np.arange(3)*np.arange(3).transpose())

5